<?xml version="1.0" encoding="UTF-8"?><testrun name="AssignmentTest (1)" project="Assignment 2" tests="9" started="9" failures="0" errors="1" ignored="0">
  <testsuite name="AssignmentTest" time="0.003">
    <testcase name="testSimplify1" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_OneValue" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_ComplexInvalid" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_OneVariable" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_OneOperator" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_ComplexValid" classname="AssignmentTest" time="0.0"/>
    <testcase name="testPrefix2tree" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_Null" classname="AssignmentTest" time="0.0"/>
    <testcase name="testIsArithmeticExpression_Simple_1" classname="AssignmentTest" time="0.003">
      <error>java.lang.IllegalArgumentException: String was not a valid arithmetic expression in prefix notation
	at Assignment.prefix2tree(Assignment.java:150)
	at Assignment.prefix2tree(Assignment.java:159)
	at Assignment.prefix2tree(Assignment.java:158)
	at Assignment.prefix2tree(Assignment.java:132)
	at AssignmentTest.testIsArithmeticExpression_Simple_1(AssignmentTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

</error>
    </testcase>
  </testsuite>
</testrun>
