<?xml version="1.0" encoding="UTF-8"?><testrun name="LinkedBinaryTreeTest" project="QuadraticHashMap" tests="9" started="9" failures="1" errors="0" ignored="0">
  <testsuite name="QuadraticHashMapTest" time="0.002">
    <testcase name="testSmallHashMap" classname="QuadraticHashMapTest" time="0.0"/>
    <testcase name="testSize" classname="QuadraticHashMapTest" time="0.0"/>
    <testcase name="testConstruction" classname="QuadraticHashMapTest" time="0.0">
      <failure>java.lang.AssertionError: Expected test to throw an instance of java.lang.RuntimeException
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="testValueSet" classname="QuadraticHashMapTest" time="0.0"/>
    <testcase name="testHashFunction_StringKey" classname="QuadraticHashMapTest" time="0.001"/>
    <testcase name="testExpansion" classname="QuadraticHashMapTest" time="0.0"/>
    <testcase name="testHashFunction_IntegerKey" classname="QuadraticHashMapTest" time="0.0"/>
    <testcase name="testKeySet" classname="QuadraticHashMapTest" time="0.0"/>
    <testcase name="testIsEmpty" classname="QuadraticHashMapTest" time="0.001"/>
  </testsuite>
</testrun>
